<?php

/**
 * Implements hook_menu().
 */
function islandora_video_streaming_panopto_menu() {
  return array(
    'admin/islandora/islandora_viewers/video_streaming_panopto' => array(
      'title' => 'Panopto Video Streaming',
      'description' => 'Configure the Kaltura Video Streaming Viewer',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_video_streaming_panopto_admin'),
      'file' => 'includes/panopto_admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}
/**
 * Implements hook_islandora_viewer_info().
 */
function islandora_video_streaming_panopto_islandora_viewer_info() {
  return array(
    'islandora_video_streaming_panopto' => array(
      'label' => t('Panopto'),
      'description' => t('Use Panopto video streaming service'),
      'derivative_description' => t('Upload new content to Panopto video streaming service'),
      'mimetype' => array('application/javascript'),
      'configuration' => '',
    ),
  );
}

/**
 * Implements hook_islandora_CMODEL_PID_derivative()
 * 
**/
function islandora_video_streaming_panopto_islandora_sp_videoCModel_islandora_derivative() {
  $deriviatives = array();
  if (variable_get('islandora_video_streaming_panopto_make_derivative', false)) {
    $derivatives[] = array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'PANOPTO_INFO',
      'weight' => '0',
      'function' => array(
        'islandora_video_streaming_panopto_upload',
      ),
      'file' => drupal_get_path('module', 'islandora_video_streaming') . '/includes/panopto_derivatives.inc',
    );
  }
  return $derivatives; 
}

/**
 * Change output for streaming capable videos, when appropriate
 * implements hook_process_islandora_video
 *
 * @var $variables array The page content variables
 */
function islandora_video_streaming_panopto_process_islandora_video($variables = array()) {
  $object = $variables['object'];
  $streamDatastream = 'PANOPTO_INFO';
  dpm("here");
  // If a streaming datastream is available, and if configured to stream
  if ($object[$streamDatastream] && variable_get('islandora_video_streaming_viewers')) {
    // get the viewer params of PID and URL
    //$params = array('url' => $object[$streamDatastream]->url);
    // get a streaming viewer instance
    dpm("Inside the first if statement");
    $new_content = '<iframe src="https://pitt.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=99e8503e-2e84-44ab-ac95-abfa014e4d06&autoplay=false&offerviewer=true&showtitle=false&showbrand=false&start=0&interactivity=search" style="width: 720px; height: 405px; border: 1px solid #464646;" allowfullscreen allow="autoplay"></iframe>'; // TODO: theme a Panopto viewer
    // if the viewer was created successfully, overwrite the non-streaming viewer
    if (isset($new_content) && $new_content) {
      dpm($new_content);
      $variables['islandora_content'] = $new_content;
    }
  }
}

function islandora_video_streaming_panopto_libraries_info() {
  $libraries['aws'] = array(
    'name' => 'aws library', 
    'vendor url' => 'https://aws.amazon.com/', 
    'download url' => 'https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.zip', 
    'version arguments' => array(
      'file' => 'README.md',
      'pattern' => '/Version (\d+)/', 
    ), 
    'files' => array(
      'php' => array('aws-autoloader.php'),
    ),
  );
  return $libraries;
}